

CREATE TABLE SUMMARY (
CHID         VARCHAR2(10) ,
NAME         VARCHAR2(10),
ID_KEY       VARCHAR2(10) );


Insert into EXPORT_TABLE (CHID,NAME,ID_KEY) values ('1001','MED1','GEN');
Insert into EXPORT_TABLE (CHID,NAME,ID_KEY) values ('1001','GEN1','MED');
Insert into EXPORT_TABLE (CHID,NAME,ID_KEY) values ('1002','MED2','GEN');
Insert into EXPORT_TABLE (CHID,NAME,ID_KEY) values ('1002','GEN2','MED');
Insert into EXPORT_TABLE (CHID,NAME,ID_KEY) values ('1003','MED3','GEN');
Insert into EXPORT_TABLE (CHID,NAME,ID_KEY) values ('1003','GEN3','MED');
Insert into EXPORT_TABLE (CHID,NAME,ID_KEY) values ('1004','MED4','GEN');
Insert into EXPORT_TABLE (CHID,NAME,ID_KEY) values ('1004','GEN4','MED');